# GET http://localhost:5000/get/todos
# Content-Type: application/json

# POST http://localhost:5000/post/create-todos
# Content-Type: application/json

# {
#       "title": "new prisma 201",
#       "body": "Learning new prisma"
#     }

# GET http://localhost:5000/get/single-todos?title=exprsess
# Content-Type: application/json    


# PATCH  http://localhost:5000/update/todos?title=express
# Content-Type: application/json  

# {
#     "body": "Learning newasd prisma express and gin"
# }

DELETE   http://localhost:5000/todos?title=newprismaoka
Content-Type: application/json